### ISSUE TITLE
same aggreegate

### ISSUE THREAD

**Issue by fewensa** [darwinia-network/ormpipe#18]
```
debug:   2023-10-20T09:46:30Z | [ormpipe-relay] [ arbitrum-sepolia>crab ] [oracle:aggregate] aggregate beacons ["0x2fd21a8737ca87096bcf980ba0483c02758c1f95b35ad07cedd9b56816cf2923","0x384e8e9f748a53658f79411bea3bcf7a7ef61d0e3f61b44f416c8f1993ebe14f","0x4fdf0d44d4f68400d4f19f3d63dc286b67a44bc94d306de94c5d82fa38149daa","0x6a7514b776b3aee03852463f58145f082c52e70327034dfdc240150849b1e178"] to crab subapi contract
debug:   2023-10-20T09:46:30Z | [ormpipe-relay] [       contract        ] [      crab      ] call crab -> subapi.aggregateBeacons ["0x2fd21a8737ca87096bcf980ba0483c02758c1f95b35ad07cedd9b56816cf2923","0x384e8e9f748a53658f79411bea3bcf7a7ef61d0e3f61b44f416c8f1993ebe14f","0x4fdf0d44d4f68400d4f19f3d63dc286b67a44bc94d306de94c5d82fa38149daa","0x6a7514b776b3aee03852463f58145f082c52e70327034dfdc240150849b1e178"]
debug:   2023-10-20T09:46:30Z | [ormpipe-relay] [      ethers:crab      ] [ sendRpcPayload ] [{"method":"eth_getTransactionCount","params":["0x0b001c95e86d64c1ad6e43944c568a6c31b53887","pending"],"id":27,"jsonrpc":"2.0"},{"method":"eth_chainId","params":[],"id":28,"jsonrpc":"2.0"}]
debug:   2023-10-20T09:46:31Z | [ormpipe-relay] [      ethers:crab      ] [receiveRpcResult] [{"jsonrpc":"2.0","result":"0xab","id":27},{"jsonrpc":"2.0","result":"0x2c","id":28}]
debug:   2023-10-20T09:46:31Z | [ormpipe-relay] [      ethers:crab      ] [ sendRpcPayload ] {"method":"eth_estimateGas","params":[{"nonce":"0xab","from":"0x0b001c95e86d64c1ad6e43944c568a6c31b53887","to":"0x001f4321429b1e2df774bdae0fc62a7394652e0f","data":"0x8cdd8844000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000042fd21a8737ca87096bcf980ba0483c02758c1f95b35ad07cedd9b56816cf2923384e8e9f748a53658f79411bea3bcf7a7ef61d0e3f61b44f416c8f1993ebe14f4fdf0d44d4f68400d4f19f3d63dc286b67a44bc94d306de94c5d82fa38149daa6a7514b776b3aee03852463f58145f082c52e70327034dfdc240150849b1e178"}],"id":29,"jsonrpc":"2.0"}
debug:   2023-10-20T09:46:31Z | [ormpipe-relay] [      ethers:crab      ] [receiveRpcResult] [{"jsonrpc":"2.0","error":{"code":-32603,"message":"VM Exception while processing transaction: revert same","data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000473616d6500000000000000000000000000000000000000000000000000000000"},"id":29}]
error:   2023-10-20T09:46:31Z | [ormpipe-relay] [ arbitrum-sepolia>crab ] execution reverted: "same" (action="estimateGas", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000473616d6500000000000000000000000000000000000000000000000000000000", reason="same", transaction={ "data": "0x8cdd8844000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000042fd21a8737ca87096bcf980ba0483c02758c1f95b35ad07cedd9b56816cf2923384e8e9f748a53658f79411bea3bcf7a7ef61d0e3f61b44f416c8f1993ebe14f4fdf0d44d4f68400d4f19f3d63dc286b67a44bc94d306de94c5d82fa38149daa6a7514b776b3aee03852463f58145f082c52e70327034dfdc240150849b1e178", "from": "0x0b001c95E86D64C1Ad6e43944C568A6C31b53887", "to": "0x001F4321429B1E2DF774bdAe0fc62A7394652E0F" }, invocation=null, revert={ "args": [ "same" ], "name": "Error", "signature": "Error(string)" }, code=CALL_EXCEPTION, version=6.7.1)
Error: execution reverted: "same" (action="estimateGas", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000473616d6500000000000000000000000000000000000000000000000000000000", reason="same", transaction={ "data": "0x8cdd8844000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000042fd21a8737ca87096bcf980ba0483c02758c1f95b35ad07cedd9b56816cf2923384e8e9f748a53658f79411bea3bcf7a7ef61d0e3f61b44f416c8f1993ebe14f4fdf0d44d4f68400d4f19f3d63dc286b67a44bc94d306de94c5d82fa38149daa6a7514b776b3aee03852463f58145f082c52e70327034dfdc240150849b1e178", "from": "0x0b001c95E86D64C1Ad6e43944C568A6C31b53887", "to": "0x001F4321429B1E2DF774bdAe0fc62A7394652E0F" }, invocation=null, revert={ "args": [ "same" ], "name": "Error", "signature": "Error(string)" }, code=CALL_EXCEPTION, version=6.7.1)
    at makeError (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/utils/errors.js:125:21)
    at getBuiltinCallException (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/abi/abi-coder.js:104:37)
    at AbiCoder.getBuiltinCallException (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/abi/abi-coder.js:201:16)
    at JsonRpcProvider.getRpcError (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/providers/provider-jsonrpc.js:599:43)
    at /data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/providers/provider-jsonrpc.js:268:45
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by fewensa** [comment]
```
debug:   2023-10-20T09:47:23Z | [ormpipe-relay] [       contract        ] [      crab      ] call crab -> subapi.aggregateBeacons ["0x2fd21a8737ca87096bcf980ba0483c02758c1f95b35ad07cedd9b56816cf2923","0x384e8e9f748a53658f79411bea3bcf7a7ef61d0e3f61b44f416c8f1993ebe14f","0x4fdf0d44d4f68400d4f19f3d63dc286b67a44bc94d306de94c5d82fa38149daa","0x6a7514b776b3aee03852463f58145f082c52e70327034dfdc240150849b1e178"]
debug:   2023-10-20T09:47:23Z | [ormpipe-relay] [      ethers:crab      ] [ sendRpcPayload ] [{"method":"eth_chainId","params":[],"id":1,"jsonrpc":"2.0"},{"method":"eth_getTransactionCount","params":["0x0b001c95e86d64c1ad6e43944c568a6c31b53887","pending"],"id":2,"jsonrpc":"2.0"},{"method":"eth_chainId","params":[],"id":3,"jsonrpc":"2.0"}]
debug:   2023-10-20T09:47:24Z | [ormpipe-relay] [      ethers:crab      ] [receiveRpcResult] [{"jsonrpc":"2.0","result":"0x2c","id":1},{"jsonrpc":"2.0","result":"0xac","id":2},{"jsonrpc":"2.0","result":"0x2c","id":3}]
debug:   2023-10-20T09:47:24Z | [ormpipe-relay] [      ethers:crab      ] [ sendRpcPayload ] {"method":"eth_estimateGas","params":[{"nonce":"0xac","from":"0x0b001c95e86d64c1ad6e43944c568a6c31b53887","to":"0x001f4321429b1e2df774bdae0fc62a7394652e0f","data":"0x8cdd8844000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000042fd21a8737ca87096bcf980ba0483c02758c1f95b35ad07cedd9b56816cf2923384e8e9f748a53658f79411bea3bcf7a7ef61d0e3f61b44f416c8f1993ebe14f4fdf0d44d4f68400d4f19f3d63dc286b67a44bc94d306de94c5d82fa38149daa6a7514b776b3aee03852463f58145f082c52e70327034dfdc240150849b1e178"}],"id":4,"jsonrpc":"2.0"}
debug:   2023-10-20T09:47:25Z | [ormpipe-relay] [      ethers:crab      ] [receiveRpcResult] [{"jsonrpc":"2.0","error":{"code":-32603,"message":"VM Exception while processing transaction: revert !agg","data":"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000042161676700000000000000000000000000000000000000000000000000000000"},"id":4}]
error:   2023-10-20T09:47:25Z | [ormpipe-relay] [ arbitrum-sepolia>crab ] execution reverted: "!agg" (action="estimateGas", data="0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000042161676700000000000000000000000000000000000000000000000000000000", reason="!agg", transaction={ "data": "0x8cdd8844000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000042fd21a8737ca87096bcf980ba0483c02758c1f95b35ad07cedd9b56816cf2923384e8e9f748a53658f79411bea3bcf7a7ef61d0e3f61b44f416c8f1993ebe14f4fdf0d44d4f68400d4f19f3d63dc286b67a44bc94d306de94c5d82fa38149daa6a7514b776b3aee03852463f58145f082c52e70327034dfdc240150849b1e178", "from": "0x0b001c95E86D64C1Ad6e43944C568A6C31b53887", "to": "0x001F4321429B1E2DF774bdAe0fc62A7394652E0F" }, invocation=null, revert={ "args": [ "!agg" ], "name": "Error", "signature": "Error(string)" }, code=CALL_EXCEPTION, version=6.7.1)
Error: execution reverted: "!agg" (action="estimateGas", data="0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000042161676700000000000000000000000000000000000000000000000000000000", reason="!agg", transaction={ "data": "0x8cdd8844000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000042fd21a8737ca87096bcf980ba0483c02758c1f95b35ad07cedd9b56816cf2923384e8e9f748a53658f79411bea3bcf7a7ef61d0e3f61b44f416c8f1993ebe14f4fdf0d44d4f68400d4f19f3d63dc286b67a44bc94d306de94c5d82fa38149daa6a7514b776b3aee03852463f58145f082c52e70327034dfdc240150849b1e178", "from": "0x0b001c95E86D64C1Ad6e43944C568A6C31b53887", "to": "0x001F4321429B1E2DF774bdAe0fc62A7394652E0F" }, invocation=null, revert={ "args": [ "!agg" ], "name": "Error", "signature": "Error(string)" }, code=CALL_EXCEPTION, version=6.7.1)
    at makeError (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/utils/errors.js:125:21)
    at getBuiltinCallException (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/abi/abi-coder.js:104:37)
    at AbiCoder.getBuiltinCallException (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/abi/abi-coder.js:201:16)
    at JsonRpcProvider.getRpcError (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/providers/provider-jsonrpc.js:599:43)
    at /data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/providers/provide
```

**Comment by fewensa** [comment]
fixed by https://github.com/darwinia-network/ormpipe/pull/15
