### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by fewensa** [darwinia-network/ormpipe#37]
```

info:    2024-01-30T05:44:43Z | --------- oracle crab>sepolia ---------
info:    2024-01-30T05:44:45Z | [ormpipe-relay-oracle] [crab>sepolia] [oracle:sign] new message accepted 0x91f3fd7b6d1f8c39cc60fa7f96f8cce5b7090bc088ae58c7f71b68b945722906 wait block 2188051(crab) finalized
info:    2024-01-30T05:44:46Z | [ormpipe-relay-oracle] [crab>sepolia] [oracle:sign] message block finalized 2188125/2188051(crab)
info:    2024-01-30T05:44:47Z | [ormpipe-relay-oracle] [crab>sepolia] [oracle:sign] sign message 1329 again, wait other node to sign this message
info:    2024-01-30T05:45:18Z | [ormpipe-relay-oracle] [crab>sepolia] [oracle:sign] message 1329(crab) is signed and submit to signcribe: 0x86af6a31dce7d95641e19af5c7c5d221bd3a32cd78a3272046e2179373246a46
error:   2024-01-30T05:45:18Z | [   ormpipe-relay    ] [crab>sepolia] invalid BytesLike value (argument="value", value="a34a98021b7b0991cdd271ace9bdf7c78aae95da8aad98f91ec395e9de21f10a15e285df7bf360c4f7f626ed963d066732889557960213297d7bd5f9a06a23ec1b0xa34a98021b7b0991cdd271ace9bdf7c78aae95da8aad98f91ec395e9de21f10a15e285df7bf360c4f7f626ed963d066732889557960213297d7bd5f9a06a23ec1b0xdb56faa649171c00f9cda50d681f8e9362bb0f152b347a549879299eccba6be2255dd92ea941a87e673b852745d7be1241d5da725187e6c8f7b8817abcf4b1af1c", code=INVALID_ARGUMENT, version=6.7.1)
TypeError: invalid BytesLike value (argument="value", value="a34a98021b7b0991cdd271ace9bdf7c78aae95da8aad98f91ec395e9de21f10a15e285df7bf360c4f7f626ed963d066732889557960213297d7bd5f9a06a23ec1b0xa34a98021b7b0991cdd271ace9bdf7c78aae95da8aad98f91ec395e9de21f10a15e285df7bf360c4f7f626ed963d066732889557960213297d7bd5f9a06a23ec1b0xdb56faa649171c00f9cda50d681f8e9362bb0f152b347a549879299eccba6be2255dd92ea941a87e673b852745d7be1241d5da725187e6c8f7b8817abcf4b1af1c", code=INVALID_ARGUMENT, version=6.7.1)
    at makeError (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/utils/errors.js:118:21)
    at assert (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/utils/errors.js:142:15)
    at assertArgument (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/utils/errors.js:154:5)
    at _getBytes (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/utils/data.js:27:36)
    at getBytesCopy (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/utils/data.js:48:12)
    at BytesCoder.encode (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/abi/coders/bytes.js:17:45)
    at /data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/abi/coders/array.js:39:19
    at Array.forEach (<anonymous>)
    at pack (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/abi/coders/array.js:33:12)
    at TupleCoder.encode (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/abi/coders/tuple.js:60:36)
/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/utils/errors.js:125
            error = new Error(message);
                    ^

Error: network does not support ENS (operation="getEnsAddress", info={ "network": { "chainId": "44", "name": "unknown" } }, code=UNSUPPORTED_OPERATION, version=6.7.1)
    at makeError (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/utils/errors.js:125:21)
    at assert (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/utils/errors.js:142:15)
    at EnsResolver.getEnsAddress (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/providers/ens-resolver.js:444:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async #getResolver (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/providers/ens-resolver.js:450:25)
    at async EnsResolver.fromName (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/providers/ens-resolver.js:486:26)
    at async JsonRpcProvider.getResolver (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/providers/abstract-provider.js:819:16)
    at async JsonRpcProvider.resolveName (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/providers/abstract-provider.js:829:26)
    at async Wallet.resolveName (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/providers/abstract-signer.js:178:16)
    at async Contract.getAddress (/data/dev/darwinia-network/ormpipe/node_modules/ethers/lib.commonjs/contract/contract.js:652:33) {
  code: 'UNSUPPORTED_OPERATION',
  operation: 'getEnsAddress',
  info: { network: Network {} }
}

Node.js v18.14.2
```

**Comment by fewensa** [comment]
wrong sign data

**Comment by fewensa** [comment]
fixed #38
